---
title: "Example longitudinal data"
author: "Juan R Gonzalez"
date: "16 de mayo de 2019"
output: 
  BiocStyle::html_document:
    toc_depth: 3
  BiocStyle::pdf_document:
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "",
                      message = FALSE, warning = FALSE,
                      cache=TRUE)
```


# Load data

```{r load}
setwd("c:/juan/CREAL/GitHub/PrivateTeachingMaterials/advanced_modelling_R/data")
dat <- read.delim("Base_Curso_F4D.txt", dec=",", 
                  na.strings = c("#N/A"))
                    
head(dat)
str(dat)
```


# Data in long format

```{r long2}

vars <- grep("^P.CINTURA", names(dat), value = TRUE)

datS <- dat[ , c("ID_FAMILIAR", "ZONA", vars)]

cint <- reshape(datS, direction="long",
                varying = list(vars),
                idvar = c("ID_FAMILIAR","ZONA"),
                v.names = c("cintura"),
                timevar = "tiempo", times=1:9)
head(cint)

cint$familia <- substr(cint$ID_FAMILIAR, 1, 8)
head(cint)


write.table(cint, file="cintura.txt", sep="\t", quote=FALSE,
            row.names = FALSE)
```


```{r long}
vars <- grep("^GLUC", names(dat), value = TRUE)

datS <- dat[ , c("ID_FAMILIAR", "ZONA", vars)]

head(datS)

gluc <- reshape(datS, direction="long",
                varying = list(grep("^GLUC", names(dat), value = TRUE)),
                idvar = c("ID_FAMILIAR","ZONA"),
                v.names = c("glucosa"),
                timevar = "tiempo", times=1:3)
gluc$familia <- substr(gluc$ID_FAMILIAR, 1, 8)
head(gluc)

write.table(gluc, file="glucosa.txt", sep="\t", quote=FALSE,
            row.names = FALSE)
```


# Analysis: cintura

```{r cint}
library(nlme)
cint.s <- groupedData(cintura ~ tiempo | ID_FAMILIAR, cint)
plot(cint.s)
```

```{r plot2}
library(ggplot2)

cint.agg <- aggregate(cintura ~ tiempo + ZONA, cint, mean)

plt <- ggplot(cint, aes(x = tiempo, y = cintura, color=ZONA)) +
    geom_line(aes(group = ZONA), alpha = .3) +
    geom_line(data = cint.agg, alpha = .8, size = 3) +
    scale_color_manual(values=c("darkgreen", "lightgreen"))
plt
```

```{r model}
library(nlme)
mod.cint1 <- lme(cintura ~ tiempo*ZONA, cint.s, 
                random = ~ 1, na.action="na.omit")
mod.cint2 <- lme(cintura ~ tiempo*ZONA, cint.s, 
                random = ~ tiempo, na.action = "na.omit")
anova(mod.cint1, mod.cint2)

summary(mod.cint1)
summary(mod.cint2)
``` 


```{r resid}
plot(mod.cint1)
plot(mod.cint2)
```


# Analysis: glucosa

```{r gluc}
gluc.s <- groupedData(glucosa ~ tiempo | ID_FAMILIAR, gluc)
plot(gluc.s)
```

```{r plot22}
gluc <- subset(gluc, glucosa < 200)
gluc.agg <- aggregate(glucosa ~ tiempo + ZONA, gluc, mean)

plt <- ggplot(gluc, aes(x = tiempo, y = glucosa, color=ZONA)) +
    geom_line(aes(group = ZONA), alpha = .3) +
    geom_line(data = gluc.agg, alpha = .8, size = 3) +
    scale_color_manual(values=c("darkgreen", "lightgreen"))
plt + ylim(c(80, 110))
```

```{r mod_gluc}
mod.gluc <- lme(glucosa ~ tiempo*ZONA, gluc.s, 
                random = ~ 1)
summary(mod.gluc)
```